### ISSUE TITLE
Different branch meanings and operating conditions

### ISSUE THREAD

**Issue by Cristian-wp** [norlab-ulaval/norlab_icp_mapper#8]
Hello, I am trying to understand how to make this package work.
I am trying to use it in a really bad enviroment: is a tunnel of 300m with flat concrete walls, no window, colums, signals, really nothing.
Now I am trying to investigate the darpa branch, because I think is the best fitting one.
Can you please suggest me the bests than can be usefull in my case?
Thanks in advance.

**Comment by kubelvla** [comment]
@vdsmax Are you able to find the yaml configuration files that we used for the finals? @Cristian-wp The specifics of this branch are mainly about the integration to our SubT competition system. Maxime might give you the necessary yaml files that configure the ICP to the state that worked the best for us (we were using 16-beam lidars in the Urban circuit, and then also some 128-beam for the finals, but we subsampled them anyway). If you have a straight tunnel without any geometrical features, you may use the trick with two robots, one moving while the other being static and vice-versa, this may provide the necessary feature. Otherwise, the mapping will probably converge to what your prior says, along the tunnel direction at least.

**Comment by Cristian-wp** [comment]
@kubelvla Thank you for your answer, but...
What do you mean with "Otherwise, the mapping will probably converge to what your prior says, along the tunnel direction at least.h "?
For what concern the lidar sensor, at the moment we can use a velodyne VLP-16 or a Ouster OS0-64 (not at the same time).
@vdsmax if you can provide the yaml's it will be great! Thank you a lot.

Do you think that for my purpose I have to work with this branch or I have to work with another?

**Comment by kubelvla** [comment]
I've been just running the mapper on a dataset from an underground mine, and it works with ok-ish, but I needed to increase the map density and update rate, just because there is not so many features on the walls (just irregularities). See the screenshot:
![image](https://user-images.githubusercontent.com/5738314/194544833-af2b2c4b-372a-4fac-8475-5577c802c284.png)

**Comment by Cristian-wp** [comment]
Hi thanks a lot for your reply.
I have try to follow your suggestions (with the darpa one) but I can not manage to get a "good" map like yours.(screen below)
This are my actual parameters in the norlab_icp_mapper_ros package (I put them in a launch file). Can you suggest me which one are to tune in order to get something similar to yours?
```
<!-- icp ros params -->
    <param name="odom_frame" value="odom" />
    <param name="robot_frame" value="base_link" />
    <param name="sensor_frame" value="os_sensor_sync" />
    <param name="initial_map_file_name" value="" />
    <param name="initial_robot_pose" value="[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]" /> <!-- identity matrix -->
    <param name="final_map_file_name" value="map.vtk" />
    <param name="final_trajectory_file_name" value="trajectory.vtk" />
    <param name="icp_config" value="" />
    <param name="input_filters_config" value="" />
    <param name="map_post_filters_config" value="" />
    <param name="map_update_condition" value="overlap" /> <!-- "overlap", "delay", "distance" -->
    <param name="map_update_overlap" value= "0.9" />
    <param name="map_update_delay" value="1" />
    <param name="map_update_distance" value="1" />
    <param name="map_publish_rate" value="1" />
    <param name="map_tf_publish_rate" value="100" /> <!-- rate of the IMU -->
    <param name="max_idle_time" value="10" />
    <param name="min_dist_new_point" value="0.03" />
    <param name="sensor_max_range" value="20" />
    <param name="prior_dynamic" value="0.6" />
    <param name="threshold_dynamic" value="0.9" />
    <param name="beam_half_angle" value="0.01" />
    <param name="epsilon_a" value="0.01" />
    <param name="epsilon_d" value="0.01" />
    <param name="alpha" value="0.8" />
    <param name="beta" value="0.99" />
    <param name="consecutive_convergence_errors_before_failure" value="5" />
    <param name="is_3D" value="true" />
    <param name="is_online" value="true" />
    <param name="compute_prob_dynamic" value="false" />
    <param name="is_mapping" value="true" />
    <param name="save_map_cells_on_hard_drive" value="false" />
    <param name="publish_tfs_between_registrations" value="true" />
    <param name="backup_in_ram" value="false" />
```
![rviz_screenshot_2022_10_07-14_24_36](https://user-images.githubusercontent.com/61200634/194553956-3aa00097-cf6a-41a1-aa32-3ca499b0cf8c.png)

**Comment by kubelvla** [comment]
My launch file for the mine is quite simple:
`<node pkg="norlab_icp_mapper_ros" type="mapper_node" name="mapper_node" output="screen" >
		<remap from="points_in" to="/ouster/points_deskewed"/>
		<param name="robot_frame" value="base_link"/>
		<param name="odom_frame" value="odom"/>
		<param name="icp_config" value="$(find alina_launchers)/params/realtime_icp_config.yaml"/>
		<param name="input_filters_config" value="$(find alina_launchers)/params/realtime_input_filters.yaml"/>
		<param name="map_post_filters_config" value="$(find alina_launchers)/params/realtime_post_filters.yaml"/>
		<param name="map_update_condition" value="delay"/>
		<param name="map_update_delay" value="0.1"/>
		<param name="sensor_max_range" value="40"/>
		<param name="min_dist_new_point" value="0.1"/>
		<param name="compute_prob_dynamic" value="true"/>
		<param name="map_tf_publish_rate" value="100"/>
	</node>`

**Comment by kubelvla** [comment]
But the trick is in the ICP config, the default ones are too crude.
The icp config:
```
matcher:
  KDTreeMatcher:
    knn: 6
    maxDist: 2.0
    epsilon: 1


outlierFilters:
 - TrimmedDistOutlierFilter:
    ratio: 0.7


errorMinimizer:
  PointToPlaneErrorMinimizer:

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 1000000.1
      maxTranslationNorm: 15000.00

inspector:
  NullInspector

logger:
  NullLogger

```

**Comment by kubelvla** [comment]
The input filters:
```
- BoundingBoxDataPointsFilter:
    xMin: -1.5
    xMax: 0.5
    yMin: -1
    yMax: 1
    zMin: -1
    zMax: 0.5
    removeInside: 1

- RandomSamplingDataPointsFilter:
    prob: 0.5

-ObservationDirectionDataPointsFilter:

```
Note here that we use the bounding box filter to remove the robotic platform itself

**Comment by kubelvla** [comment]
The post-processing filters:
```
- CutAtDescriptorThresholdDataPointsFilter:
    descName: probabilityDynamic
    useLargerThan: 1
    threshold: 0.8

- SurfaceNormalDataPointsFilter:
    knn: 15

```
The first one removes stuff considered dynamic, and the second filter recomputes the surface normals based on the final map pointcloud (otherwise, normals computed from the input pointcloud are kept and used for future matching)
